import { HiOutlineHome, HiOutlineMail, HiOutlineUsers } from "react-icons/hi";
import { TbCalendar, TbChartHistogram, TbFile, TbFileInvoice, TbLockAccess, TbUsers } from "react-icons/tb";
import { FaRegCalendarAlt, FaTelegramPlane, FaWhatsapp } from "react-icons/fa";
import {
  RiFileList3Line,
  RiHeartLine,
  RiImageLine,
  RiLockPasswordLine,
  RiMedicineBottleLine,
  RiMoneyDollarCircleLine,
  RiStethoscopeLine,
  RiUserHeartLine,
  RiUserLine,
} from "react-icons/ri";
import { MdListAlt, MdOutlineAttachMoney, MdOutlineCampaign, MdOutlineInventory2, MdOutlineTextsms } from "react-icons/md";
import { AiOutlineSetting } from "react-icons/ai";
import { BiCalendar, BiUserPlus } from "react-icons/bi";
import { useSelector } from "react-redux";

const MenuDatas = () => {
  const roles = useSelector((state) => state.roles);
  if (roles === "Pharmacist") {
    return [
      {
        title: "Dashboard",
        path: "/dashboard",
        icon: HiOutlineHome,
      },
      {
        title: "Medicine",
        path: "/medicine",
        icon: RiMedicineBottleLine,
      },
      {
        title: "Payments",
        path: "/payments",
        icon: MdListAlt,
      },
      {
        title: "Invoices",
        path: "/invoices",
        icon: TbFileInvoice,
      },
      {
        title: "Settings",
        path: "/settings",
        icon: AiOutlineSetting,
      },
    ];
  } else if (roles === "Doctors") {
    return [
      {
        title: "Dashboard",
        path: "/dashboard",
        icon: HiOutlineHome,
      },
      {
        title: "Patients",
        path: "/patients",
        icon: TbUsers,
      },
      {
        title: "Appointments",
        path: "/appointments",
        icon: FaRegCalendarAlt,
      },
      {
        title: "Payments",
        path: "/payments",
        icon: MdListAlt,
      },
      {
        title: "Invoices",
        path: "/invoices",
        icon: TbFileInvoice,
      },
      {
        title: "Settings",
        path: "/settings",
        icon: AiOutlineSetting,
      },
    ];
  } else if (roles === "Nurses") {
    return [
      {
        title: "Dashboard",
        path: "/dashboard",
        icon: HiOutlineHome,
      },
      {
        title: "Patients",
        path: "/patients",
        icon: TbUsers,
      },
      {
        title: "Appointments",
        path: "/appointments",
        icon: FaRegCalendarAlt,
      },
      {
        title: "Payments",
        path: "/payments",
        icon: MdListAlt,
      },
      {
        title: "Invoices",
        path: "/invoices",
        icon: TbFileInvoice,
      },
      {
        title: "Settings",
        path: "/settings",
        icon: AiOutlineSetting,
      },
    ];
  } else if (roles === "Receptionist") {
    return [
      {
        title: "Dashboard",
        path: "/dashboard",
        icon: HiOutlineHome,
      },
      {
        title: "Patients",
        path: "/patients",
        icon: TbUsers,
      },
      {
        title: "Appointments",
        path: "/appointments",
        icon: FaRegCalendarAlt,
      },
      {
        title: "Settings",
        path: "/settings",
        icon: AiOutlineSetting,
      },
    ];
  } else {
    return [
      {
        title: "Dashboard",
        path: "/dashboard",
        icon: HiOutlineHome,
      },
      {
        title: "Patients",
        path: "/patients",
        icon: TbUsers,
      },
      {
        title: "Receptions",
        path: "/receptions",
        icon: HiOutlineUsers,
      },
      {
        title: "Nurses",
        path: "/nurses",
        icon: HiOutlineUsers,
      },
      {
        title: "Doctors",
        path: "/doctors",
        icon: RiUserHeartLine,
      },

      {
        title: "Appointments",
        path: "/appointments",
        icon: FaRegCalendarAlt,
      },
      {
        title: "Payments",
        path: "/payments",
        icon: MdListAlt,
      },
      {
        title: "Invoices",
        path: "/invoices",
        icon: TbFileInvoice,
      },
      {
        title: "Services",
        path: "/services",
        icon: MdOutlineInventory2,
      },
      {
        title: "Medicine",
        path: "/medicine",
        icon: RiMedicineBottleLine,
      },
      {
        title: "Campaigns",
        path: "/campaigns",
        icon: MdOutlineCampaign,
      },
      {
        title: "Settings",
        path: "/settings",
        icon: AiOutlineSetting,
      },
    ];
  }
};
export default MenuDatas;
export const memberData = [
  {
    id: 1,
    title: "Hugo Lloris",
    image: "/images/user1.png",
    admin: false,
    email: "hugolloris@gmail.com",
    phone: "+1 234 567 890",
    age: 25,
    gender: "Male",
    blood: "A+",
    totalAppointments: 5,
    date: "20 Aug 2021",
  },
  {
    id: 2,
    title: "Mauris auctor",
    image: "/images/user2.png",
    admin: false,
    email: "maurisauctor@gmail.com",
    phone: "+1 456 789 123",
    age: 34,
    gender: "Female",
    blood: "B+",
    totalAppointments: 3,
    date: "22 Nov 2023",
  },
  {
    id: 3,
    title: "Michael Owen",
    image: "/images/user3.png",
    admin: false,
    phone: "+1 890 123 456",
    email: "michaelowen@gmail.com",
    age: 45,
    gender: "Male",
    blood: "O+",
    totalAppointments: 26,
    date: "12 Jan 2020",
  },
  {
    id: 4,
    title: "Amina Smith",
    image: "/images/user4.png",
    admin: true,
    phone: "+1 908 765 432",
    email: "aminasmith@gmail.com",
    age: 28,
    gender: "Female",
    blood: "AB+",
    totalAppointments: 17,
    date: "07 Feb 2001",
  },
  {
    id: 5,
    title: "Minahil Khan",
    image: "/images/user5.png",
    admin: false,
    phone: "+1 890 123 456",
    email: "minahilkhan@gmail.com",
    age: 35,
    gender: "Female",
    blood: "A+",
    totalAppointments: 9,
    date: "30 Dec 2019",
  },
  {
    id: 6,
    title: "Alex Morgan",
    image: "/images/user6.png",
    admin: false,
    phone: "+1 908 765 432",
    email: "alexmorgan@gmail.com",
    age: 29,
    gender: "Male",
    blood: "B+",
    totalAppointments: 34,
    date: "12 Jan 2020",
  },
  {
    id: 7,
    title: "John Doe",
    image: "/images/user7.png",
    admin: false,
    phone: "+1 234 567 890",
    email: "johndoe@gmail.com",
    age: 32,
    gender: "Male",
    blood: "O-",
    totalAppointments: 12,
    date: "18 Mar 2023",
  },
  {
    id: 8,
    title: "David Beckham",
    image: "/images/user8.png",
    admin: false,
    phone: "+1 456 789 123",
    email: "davidbackham@gmail.com",
    age: 27,
    gender: "Female",
    blood: "AB+",
    totalAppointments: 70,
    date: "01 June 2018",
  },
];

export const sortsDatas = {
  status: [
    {
      id: 1,
      name: "Status...",
    },
    {
      id: 2,
      name: "Pending",
    },
    {
      id: 3,
      name: "Approved",
    },
    {
      id: 4,
      name: "Cancelled",
    },
  ],
  method: [
    {
      id: 1,
      name: "Payment method",
    },
    {
      id: 2,
      name: "Cash",
    },
    {
      id: 3,
      name: "NHIS Insurance",
    },
    {
      id: 4,
      name: "ORANGHIS",
    },
  ],
  currency: [
    {
      id: 1,
      name: "Select Currency",
    },
    {
      id: 2,
      name: "USD (US Dollar)",
    },
    {
      id: 3,
      name: "EUR (Euro)",
    },
    {
      id: 4,
      name: "TSH (Tanzanian Shilling)",
    },
  ],
  instractions: [
    {
      id: 1,
      name: "Select Instraction",
    },
    {
      id: 2,
      name: "After Meal",
    },
    {
      id: 3,
      name: "Before Meal",
    },
  ],
  measure: [
    {
      id: 1,
      name: "Select Measure",
    },
    {
      id: 2,
      name: "mg",
    },
    {
      id: 3,
      name: "ml",
    },
    {
      id: 4,
      name: "gm",
    },
    {
      id: 5,
      name: "kg",
    },
    {
      id: 6,
      name: "lb",
    },
    {
      id: 7,
      name: "tbsp",
    },
    {
      id: 8,
      name: "tablet",
    },
    {
      id: 9,
      name: "capsule",
    },
  ],
  stocks: [
    {
      id: 1,
      name: "All",
    },
    {
      id: 2,
      name: "Available",
    },
    {
      id: 3,
      name: "Out of Stock",
    },
  ],
  service: [
    {
      id: 1,
      name: "All",
    },
    {
      id: 2,
      name: "Enabled",
    },
    {
      id: 3,
      name: "Disabled",
    },
  ],
  title: [
    {
      id: 1,
      name: "Dr.",
    },
    {
      id: 2,
      name: "Mr.",
    },
    {
      id: 3,
      name: "Mrs.",
    },
    {
      id: 4,
      name: "Ms.",
    },
  ],
  filterPatient: [
    {
      id: 1,
      name: "Sort by...",
    },
    {
      id: 2,
      name: "Newest Patients",
    },
    {
      id: 3,
      name: "Oldest Patients",
    },
  ],
  genderFilter: [
    {
      id: 1,
      name: "Gender...",
    },
    {
      id: 2,
      name: "Female",
    },
    {
      id: 3,
      name: "Male",
    },
  ],
  bloodTypeFilter: [
    {
      id: 1,
      name: "Blood Type...",
    },
    {
      id: 2,
      name: "A+",
    },
    {
      id: 3,
      name: "A-",
    },
    {
      id: 4,
      name: "B+",
    },
    {
      id: 5,
      name: "B-",
    },
    {
      id: 6,
      name: "AB+",
    },
    {
      id: 7,
      name: "AB-",
    },
    {
      id: 8,
      name: "O+",
    },
    {
      id: 9,
      name: "O-",
    },
  ],
  dosage: [
    {
      id: 1,
      name: "Morning (M)",
      value: "morning",
    },
    {
      id: 2,
      name: "Afternoon (A)",
      value: "afternoon",
    },
    {
      id: 3,
      name: "Evening (E)",
      value: "evening",
    },
  ],
  roles: [
    {
      id: 1,
      name: "Doctors",
    },
    {
      id: 2,
      name: "Nurses",
    },
    {
      id: 3,
      name: "Receptionist",
    },
    {
      id: 4,
      name: "Pharmacist",
    },
    {
      id: 5,
      name: "Super Admin",
    },
  ],
};
export const location = [
  { id: 0, name: "Choose State..." },
  {
    id: 1,
    name: "Abia",
    code: "AB",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Aba North", lgaCode: "AB001" },
      { name: "Aba South", lgaCode: "AB002" },
      { name: "Arochukwu", lgaCode: "AB003" },
      { name: "Bende", lgaCode: "AB004" },
      { name: "Ikwuano", lgaCode: "AB005" },
      { name: "Isiala Ngwa North", lgaCode: "AB006" },
      { name: "Isiala Ngwa South", lgaCode: "AB007" },
      { name: "Isuikwuato", lgaCode: "AB008" },
      { name: "Obi Ngwa", lgaCode: "AB009" },
      { name: "Ohafia", lgaCode: "AB010" },
      { name: "Osisioma", lgaCode: "AB011" },
      { name: "Ugwunagbo", lgaCode: "AB012" },
      { name: "Ukwa East", lgaCode: "AB013" },
      { name: "Ukwa West", lgaCode: "AB014" },
      { name: "Umu Nneochi", lgaCode: "AB015" },
      { name: "Umuahia North", lgaCode: "AB016" },
      { name: "Umuahia South", lgaCode: "AB017" },
    ],
  },
  {
    id: 2,
    name: "Adamawa",
    code: "AD",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Demsa", lgaCode: "AD001" },
      { name: "Fufure", lgaCode: "AD002" },
      { name: "Ganye", lgaCode: "AD003" },
      { name: "Gayuk", lgaCode: "AD004" },
      { name: "Girei", lgaCode: "AD005" },
      { name: "Gombi", lgaCode: "AD006" },
      { name: "Hong", lgaCode: "AD007" },
      { name: "Jada", lgaCode: "AD008" },
      { name: "Lamurde", lgaCode: "AD009" },
      { name: "Madagali", lgaCode: "AD010" },
      { name: "Maiha", lgaCode: "AD011" },
      { name: "Mayo Belwa", lgaCode: "AD012" },
      { name: "Michika", lgaCode: "AD013" },
      { name: "Mubi North", lgaCode: "AD014" },
      { name: "Mubi South", lgaCode: "AD015" },
      { name: "Numan", lgaCode: "AD016" },
      { name: "Shelleng", lgaCode: "AD017" },
      { name: "Song", lgaCode: "AD018" },
      { name: "Toungo", lgaCode: "AD019" },
      { name: "Yola North", lgaCode: "AD020" },
      { name: "Yola South", lgaCode: "AD021" },
    ],
  },
  {
    id: 3,
    name: "Akwa Ibom",
    code: "AI",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Abak", lgaCode: "AI001" },
      { name: "Eastern Obolo", lgaCode: "AI002" },
      { name: "Eket", lgaCode: "AI003" },
      { name: "Esit Eket", lgaCode: "AI004" },
      { name: "Essien Udim", lgaCode: "AI005" },
      { name: "Etim Ekpo", lgaCode: "AI006" },
      { name: "Etinan", lgaCode: "AI007" },
      { name: "Ibeno", lgaCode: "AI008" },
      { name: "Ibesikpo Asutan", lgaCode: "AI009" },
      { name: "Ibiono-Ibom", lgaCode: "AI010" },
      { name: "Ika", lgaCode: "AI011" },
      { name: "Ikono", lgaCode: "AI012" },
      { name: "Ikot Abasi", lgaCode: "AI013" },
      { name: "Ikot Ekpene", lgaCode: "AI014" },
      { name: "Ini", lgaCode: "AI015" },
      { name: "Itu", lgaCode: "AI016" },
      { name: "Mbo", lgaCode: "AI017" },
      { name: "Mkpat-Enin", lgaCode: "AI018" },
      { name: "Nsit-Atai", lgaCode: "AI019" },
      { name: "Nsit-Ibom", lgaCode: "AI020" },
      { name: "Nsit-Ubium", lgaCode: "AI021" },
      { name: "Obot Akara", lgaCode: "AI022" },
      { name: "Okobo", lgaCode: "AI023" },
      { name: "Onna", lgaCode: "AI024" },
      { name: "Oron", lgaCode: "AI025" },
      { name: "Oruk Anam", lgaCode: "AI026" },
      { name: "Udung-Uko", lgaCode: "AI027" },
      { name: "Ukanafun", lgaCode: "AI028" },
      { name: "Uruan", lgaCode: "AI029" },
      { name: "Urue-Offong/Oruko", lgaCode: "AI030" },
      { name: "Uyo", lgaCode: "AI031" },
    ],
  },
  {
    id: 4,
    name: "Anambra",
    code: "AN",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Aguata", lgaCode: "AN001" },
      { name: "Anambra East", lgaCode: "AN002" },
      { name: "Anambra West", lgaCode: "AN003" },
      { name: "Anaocha", lgaCode: "AN004" },
      { name: "Awka North", lgaCode: "AN005" },
      { name: "Awka South", lgaCode: "AN006" },
      { name: "Ayamelum", lgaCode: "AN007" },
      { name: "Dunukofia", lgaCode: "AN008" },
      { name: "Ekwusigo", lgaCode: "AN009" },
      { name: "Idemili North", lgaCode: "AN010" },
      { name: "Idemili South", lgaCode: "AN011" },
      { name: "Ihiala", lgaCode: "AN012" },
      { name: "Njikoka", lgaCode: "AN013" },
      { name: "Nnewi North", lgaCode: "AN014" },
      { name: "Nnewi South", lgaCode: "AN015" },
      { name: "Ogbaru", lgaCode: "AN016" },
      { name: "Onitsha North", lgaCode: "AN017" },
      { name: "Onitsha South", lgaCode: "AN018" },
      { name: "Orumba North", lgaCode: "AN019" },
      { name: "Orumba South", lgaCode: "AN020" },
      { name: "Oyi", lgaCode: "AN021" },
    ],
  },
  {
    id: 5,
    name: "Bauchi",
    code: "BA",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Alkaleri", lgaCode: "BA001" },
      { name: "Bauchi", lgaCode: "BA002" },
      { name: "Bogoro", lgaCode: "BA003" },
      { name: "Damban", lgaCode: "BA004" },
      { name: "Darazo", lgaCode: "BA005" },
      { name: "Dass", lgaCode: "BA006" },
      { name: "Gamawa", lgaCode: "BA007" },
      { name: "Ganjuwa", lgaCode: "BA008" },
      { name: "Giade", lgaCode: "BA009" },
      { name: "Itas/Gadau", lgaCode: "BA010" },
      { name: "Jama'are", lgaCode: "BA011" },
      { name: "Katagum", lgaCode: "BA012" },
      { name: "Kirfi", lgaCode: "BA013" },
      { name: "Misau", lgaCode: "BA014" },
      { name: "Ningi", lgaCode: "BA015" },
      { name: "Shira", lgaCode: "BA016" },
      { name: "Tafawa Balewa", lgaCode: "BA017" },
      { name: "Toro", lgaCode: "BA018" },
      { name: "Warji", lgaCode: "BA019" },
      { name: "Zaki", lgaCode: "BA020" },
    ],
  },
  {
    id: 6,
    name: "Bayelsa",
    code: "BY",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Brass", lgaCode: "BY001" },
      { name: "Ekeremor", lgaCode: "BY002" },
      { name: "Kolokuma/Opokuma", lgaCode: "BY003" },
      { name: "Nembe", lgaCode: "BY004" },
      { name: "Ogbia", lgaCode: "BY005" },
      { name: "Sagbama", lgaCode: "BY006" },
      { name: "Southern Ijaw", lgaCode: "BY007" },
      { name: "Yenagoa", lgaCode: "BY008" },
    ],
  },
  {
    id: 7,
    name: "Benue",
    code: "BN",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Ado", lgaCode: "BN001" },
      { name: "Agatu", lgaCode: "BN002" },
      { name: "Apa", lgaCode: "BN003" },
      { name: "Buruku", lgaCode: "BN004" },
      { name: "Gboko", lgaCode: "BN005" },
      { name: "Guma", lgaCode: "BN006" },
      { name: "Gwer East", lgaCode: "BN007" },
      { name: "Gwer West", lgaCode: "BN008" },
      { name: "Katsina-Ala", lgaCode: "BN009" },
      { name: "Konshisha", lgaCode: "BN010" },
      { name: "Kwande", lgaCode: "BN011" },
      { name: "Logo", lgaCode: "BN012" },
      { name: "Makurdi", lgaCode: "BN013" },
      { name: "Obi", lgaCode: "BN014" },
      { name: "Ogbadibo", lgaCode: "BN015" },
      { name: "Ohimini", lgaCode: "BN016" },
      { name: "Oju", lgaCode: "BN017" },
      { name: "Okpokwu", lgaCode: "BN018" },
      { name: "Oturkpo", lgaCode: "BN019" },
      { name: "Tarka", lgaCode: "BN020" },
      { name: "Ukum", lgaCode: "BN021" },
      { name: "Ushongo", lgaCode: "BN022" },
      { name: "Vandeikya", lgaCode: "BN023" },
    ],
  },
  {
    id: 8,
    name: "Borno",
    code: "BR",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Abadam", lgaCode: "BR001" },
      { name: "Askira/Uba", lgaCode: "BR002" },
      { name: "Bama", lgaCode: "BR003" },
      { name: "Bayo", lgaCode: "BR004" },
      { name: "Biu", lgaCode: "BR005" },
      { name: "Chibok", lgaCode: "BR006" },
      { name: "Damboa", lgaCode: "BR007" },
      { name: "Dikwa", lgaCode: "BR008" },
      { name: "Gubio", lgaCode: "BR009" },
      { name: "Guzamala", lgaCode: "BR010" },
      { name: "Gwoza", lgaCode: "BR011" },
      { name: "Hawul", lgaCode: "BR012" },
      { name: "Jere", lgaCode: "BR013" },
      { name: "Kaga", lgaCode: "BR014" },
      { name: "Kala/Balge", lgaCode: "BR015" },
      { name: "Konduga", lgaCode: "BR016" },
      { name: "Kukawa", lgaCode: "BR017" },
      { name: "Kwaya Kusar", lgaCode: "BR018" },
      { name: "Mafa", lgaCode: "BR019" },
      { name: "Magumeri", lgaCode: "BR020" },
      { name: "Maiduguri", lgaCode: "BR021" },
      { name: "Marte", lgaCode: "BR022" },
      { name: "Mobbar", lgaCode: "BR023" },
      { name: "Monguno", lgaCode: "BR024" },
      { name: "Ngala", lgaCode: "BR025" },
      { name: "Nganzai", lgaCode: "BR026" },
      { name: "Shani", lgaCode: "BR027" },
    ],
  },
  {
    id: 9,
    name: "Cross River",
    code: "CR",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Abi", lgaCode: "CR001" },
      { name: "Akamkpa", lgaCode: "CR002" },
      { name: "Akpabuyo", lgaCode: "CR003" },
      { name: "Bakassi", lgaCode: "CR004" },
      { name: "Bekwarra", lgaCode: "CR005" },
      { name: "Biase", lgaCode: "CR006" },
      { name: "Boki", lgaCode: "CR007" },
      { name: "Calabar Municipal", lgaCode: "CR008" },
      { name: "Calabar South", lgaCode: "CR009" },
      { name: "Etung", lgaCode: "CR010" },
      { name: "Ikom", lgaCode: "CR011" },
      { name: "Obanliku", lgaCode: "CR012" },
      { name: "Obubra", lgaCode: "CR013" },
      { name: "Obudu", lgaCode: "CR014" },
      { name: "Odukpani", lgaCode: "CR015" },
      { name: "Ogoja", lgaCode: "CR016" },
      { name: "Yakuur", lgaCode: "CR017" },
      { name: "Yala", lgaCode: "CR019" },
    ],
  },
  {
    id: 10,
    name: "Delta",
    code: "DE",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Aniocha North", lgaCode: "DE001" },
      { name: "Aniocha South", lgaCode: "DE002" },
      { name: "Bomadi", lgaCode: "DE003" },
      { name: "Burutu", lgaCode: "DE004" },
      { name: "Ethiope East", lgaCode: "DE005" },
      { name: "Ethiope West", lgaCode: "DE006" },
      { name: "Ika North East", lgaCode: "DE007" },
      { name: "Ika South", lgaCode: "DE008" },
      { name: "Isoko North", lgaCode: "DE009" },
      { name: "Isoko South", lgaCode: "DE010" },
      { name: "Ndokwa East", lgaCode: "DE011" },
      { name: "Ndokwa West", lgaCode: "DE012" },
      { name: "Okpe", lgaCode: "DE013" },
      { name: "Oshimili North", lgaCode: "DE014" },
      { name: "Oshimili South", lgaCode: "DE015" },
      { name: "Patani", lgaCode: "DE016" },
      { name: "Sapele", lgaCode: "DE017" },
      { name: "Udu", lgaCode: "DE018" },
      { name: "Ughelli North", lgaCode: "DE019" },
      { name: "Ughelli South", lgaCode: "DE020" },
      { name: "Ukwuani", lgaCode: "DE021" },
      { name: "Uvwie", lgaCode: "DE022" },
      { name: "Warri North", lgaCode: "DE023" },
      { name: "Warri South", lgaCode: "DE024" },
      { name: "Warri South West", lgaCode: "DE025" },
    ],
  },
  {
    id: 11,
    name: "Ebonyi",
    code: "EB",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Abakaliki", lgaCode: "EB001" },
      { name: "Afikpo North", lgaCode: "EB002" },
      { name: "Afikpo South (Edda)", lgaCode: "EB003" },
      { name: "Ebonyi", lgaCode: "EB004" },
      { name: "Ezza North", lgaCode: "EB005" },
      { name: "Ezza South", lgaCode: "EB006" },
      { name: "Ikwo", lgaCode: "EB007" },
      { name: "Ishielu", lgaCode: "EB008" },
      { name: "Ivo", lgaCode: "EB009" },
      { name: "Izzi", lgaCode: "EB010" },
      { name: "Ohaozara", lgaCode: "EB011" },
      { name: "Ohaukwu", lgaCode: "EB012" },
      { name: "Onicha", lgaCode: "EB013" },
    ],
  },
  {
    id: 12,
    name: "Edo",
    code: "ED",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Akoko-Edo", lgaCode: "ED001" },
      { name: "Egor", lgaCode: "ED002" },
      { name: "Esan Central", lgaCode: "ED003" },
      { name: "Esan North-East", lgaCode: "ED004" },
      { name: "Esan South-East", lgaCode: "ED005" },
      { name: "Esan West", lgaCode: "ED006" },
      { name: "Etsako Central", lgaCode: "ED007" },
      { name: "Etsako East", lgaCode: "ED008" },
      { name: "Etsako West", lgaCode: "ED009" },
      { name: "Igueben", lgaCode: "ED010" },
      { name: "Ikpoba Okha", lgaCode: "ED011" },
      { name: "Orhionmwon", lgaCode: "ED012" },
      { name: "Oredo", lgaCode: "ED013" },
      { name: "Ovia North-East", lgaCode: "ED014" },
      { name: "Ovia South-West", lgaCode: "ED015" },
      { name: "Owan East", lgaCode: "ED016" },
      { name: "Owan West", lgaCode: "ED017" },
      { name: "Uhunmwonde", lgaCode: "ED018" },
    ],
  },
  {
    id: 13,
    name: "Ekiti",
    code: "EK",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Ado Ekiti", lgaCode: "EK001" },
      { name: "Gbonyin/Aiyedire", lgaCode: "EK002" },
      { name: "Efon", lgaCode: "EK003" },
      { name: "Ekiti East", lgaCode: "EK004" },
      { name: "Ekiti South-West", lgaCode: "EK005" },
      { name: "Ekiti West", lgaCode: "EK006" },
      { name: "Emure", lgaCode: "EK007" },
      { name: "Ido Osi", lgaCode: "EK008" },
      { name: "Ijero", lgaCode: "EK009" },
      { name: "Ikere", lgaCode: "EK010" },
      { name: "Ikole", lgaCode: "EK011" },
      { name: "Ilejemeje", lgaCode: "EK012" },
      { name: "Irepodun/Ifelodun", lgaCode: "EK013" },
      { name: "Ise/Orun", lgaCode: "EK014" },
      { name: "Moba", lgaCode: "EK015" },
      { name: "Oye", lgaCode: "EK016" },
    ],
  },
  {
    id: 14,
    name: "Enugu",
    code: "EN",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Aninri", lgaCode: "EN001" },
      { name: "Awgu", lgaCode: "EN002" },
      { name: "Enugu East", lgaCode: "EN003" },
      { name: "Enugu North", lgaCode: "EN004" },
      { name: "Enugu South", lgaCode: "EN005" },
      { name: "Ezeagu", lgaCode: "EN006" },
      { name: "Igbo Etiti", lgaCode: "EN007" },
      { name: "Igbo Eze North", lgaCode: "EN008" },
      { name: "Igbo Eze South", lgaCode: "EN009" },
      { name: "Isi Uzo", lgaCode: "EN010" },
      { name: "Nkanu East", lgaCode: "EN011" },
      { name: "Nkanu West", lgaCode: "EN012" },
      { name: "Nsukka", lgaCode: "EN013" },
      { name: "Oji River", lgaCode: "EN014" },
      { name: "Udenu", lgaCode: "EN015" },
      { name: "Udi", lgaCode: "EN016" },
      { name: "Uzo-Uwani", lgaCode: "EN017" },
    ],
  },
  {
    id: 15,
    name: "Gombe",
    code: "GB",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Akko", lgaCode: "GB001" },
      { name: "Balanga", lgaCode: "GB002" },
      { name: "Billiri", lgaCode: "GB003" },
      { name: "Dukku", lgaCode: "GB004" },
      { name: "Funakaye", lgaCode: "GB005" },
      { name: "Gombe", lgaCode: "GB006" },
      { name: "Kaltungo", lgaCode: "GB007" },
      { name: "Kwami", lgaCode: "GB008" },
      { name: "Nafada", lgaCode: "GB009" },
      { name: "Shongom", lgaCode: "GB010" },
      { name: "Yamaltu/Deba", lgaCode: "GB011" },
    ],
  },
  {
    id: 16,
    name: "Imo",
    code: "IM",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Aboh Mbaise", lgaCode: "IM001" },
      { name: "Ahiazu Mbaise", lgaCode: "IM002" },
      { name: "Ehime Mbano", lgaCode: "IM003" },
      { name: "Ezinihitte", lgaCode: "IM004" },
      { name: "Ideato North", lgaCode: "IM005" },
      { name: "Ideato South", lgaCode: "IM006" },
      { name: "Ihitte/Uboma", lgaCode: "IM007" },
      { name: "Ikeduru", lgaCode: "IM008" },
      { name: "Isiala Mbano", lgaCode: "IM009" },
      { name: "Isu", lgaCode: "IM010" },
      { name: "Mbaitoli", lgaCode: "IM011" },
      { name: "Ngor Okpala", lgaCode: "IM012" },
      { name: "Njaba", lgaCode: "IM013" },
      { name: "Nkwerre", lgaCode: "IM014" },
      { name: "Nwangele", lgaCode: "IM015" },
      { name: "Obowo", lgaCode: "IM016" },
      { name: "Oguta", lgaCode: "IM017" },
      { name: "Ohaji/Egbema", lgaCode: "IM018" },
      { name: "Okigwe", lgaCode: "IM019" },
      { name: "Orlu", lgaCode: "IM020" },
      { name: "Orsu", lgaCode: "IM021" },
      { name: "Oru East", lgaCode: "IM022" },
      { name: "Oru West", lgaCode: "IM023" },
      { name: "Owerri Municipal", lgaCode: "IM024" },
      { name: "Owerri North", lgaCode: "IM025" },
      { name: "Owerri West", lgaCode: "IM026" },
      { name: "Unuimo", lgaCode: "IM027" },
    ],
  },
  {
    id: 17,
    name: "Jigawa",
    code: "JI",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Auyo", lgaCode: "JI001" },
      { name: "Babura", lgaCode: "JI002" },
      { name: "Biriniwa", lgaCode: "JI003" },
      { name: "Birnin Kudu", lgaCode: "JI004" },
      { name: "Buji", lgaCode: "JI005" },
      { name: "Dutse", lgaCode: "JI006" },
      { name: "Gagarawa", lgaCode: "JI007" },
      { name: "Garki", lgaCode: "JI008" },
      { name: "Gumel", lgaCode: "JI009" },
      { name: "Guri", lgaCode: "JI010" },
      { name: "Gwaram", lgaCode: "JI011" },
      { name: "Gwiwa", lgaCode: "JI012" },
      { name: "Hadejia", lgaCode: "JI013" },
      { name: "Jahun", lgaCode: "JI014" },
      { name: "Kafin Hausa", lgaCode: "JI015" },
      { name: "Kaugama", lgaCode: "JI016" },
      { name: "Kazaure", lgaCode: "JI017" },
      { name: "Kiri Kasama", lgaCode: "JI018" },
      { name: "Kiyawa", lgaCode: "JI019" },
      { name: "Maigatari", lgaCode: "JI020" },
      { name: "Malam Madori", lgaCode: "JI021" },
      { name: "Miga", lgaCode: "JI022" },
      { name: "Ringim", lgaCode: "JI023" },
      { name: "Roni", lgaCode: "JI024" },
      { name: "Sule Tankarkar", lgaCode: "JI025" },
      { name: "Taura", lgaCode: "JI026" },
      { name: "Yankwashi", lgaCode: "JI027" },
    ],
  },
  {
    id: 18,
    name: "Kaduna",
    code: "KD",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Birnin Gwari", lgaCode: "KD001" },
      { name: "Chikun", lgaCode: "KD002" },
      { name: "Giwa", lgaCode: "KD003" },
      { name: "Igabi", lgaCode: "KD004" },
      { name: "Ikara", lgaCode: "KD005" },
      { name: "Jaba", lgaCode: "KD006" },
      { name: "Jema'a", lgaCode: "KD007" },
      { name: "Kachia", lgaCode: "KD008" },
      { name: "Kaduna North", lgaCode: "KD009" },
      { name: "Kaduna South", lgaCode: "KD010" },
      { name: "Kagarko", lgaCode: "KD011" },
      { name: "Kajuru", lgaCode: "KD012" },
      { name: "Kaura", lgaCode: "KD013" },
      { name: "Kauru", lgaCode: "KD014" },
      { name: "Kubau", lgaCode: "KD015" },
      { name: "Kudan", lgaCode: "KD016" },
      { name: "Lere", lgaCode: "KD017" },
      { name: "Makarfi", lgaCode: "KD018" },
      { name: "Sabon Gari", lgaCode: "KD019" },
      { name: "Sanga", lgaCode: "KD020" },
      { name: "Soba", lgaCode: "KD021" },
      { name: "Zangon Kataf", lgaCode: "KD022" },
      { name: "Zaria", lgaCode: "KD023" },
    ],
  },
  {
    id: 19,
    name: "Kano",
    code: "KN",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Ajingi", lgaCode: "KN001" },
      { name: "Albasu", lgaCode: "KN002" },
      { name: "Bagwai", lgaCode: "KN003" },
      { name: "Bebeji", lgaCode: "KN004" },
      { name: "Bichi", lgaCode: "KN005" },
      { name: "Bunkure", lgaCode: "KN006" },
      { name: "Dala", lgaCode: "KN007" },
      { name: "Dambatta", lgaCode: "KN008" },
      { name: "Dawakin Kudu", lgaCode: "KN009" },
      { name: "Dawakin Tofa", lgaCode: "KN010" },
      { name: "Doguwa", lgaCode: "KN011" },
      { name: "Fagge", lgaCode: "KN012" },
      { name: "Gabasawa", lgaCode: "KN013" },
      { name: "Garko", lgaCode: "KN014" },
      { name: "Garun Mallam", lgaCode: "KN015" },
      { name: "Gaya", lgaCode: "KN016" },
      { name: "Gezawa", lgaCode: "KN017" },
      { name: "Gwale", lgaCode: "KN018" },
      { name: "Gwarzo", lgaCode: "KN019" },
      { name: "Kabo", lgaCode: "KN020" },
      { name: "Kano Municipal", lgaCode: "KN021" },
      { name: "Karaye", lgaCode: "KN022" },
      { name: "Kibiya", lgaCode: "KN023" },
      { name: "Kiru", lgaCode: "KN024" },
      { name: "Kumbotso", lgaCode: "KN025" },
      { name: "Kunchi", lgaCode: "KN026" },
      { name: "Kura", lgaCode: "KN027" },
      { name: "Madobi", lgaCode: "KN028" },
      { name: "Makoda", lgaCode: "KN029" },
      { name: "Minjibir", lgaCode: "KN030" },
      { name: "Nasarawa", lgaCode: "KN031" },
      { name: "Rano", lgaCode: "KN032" },
      { name: "Rimin Gado", lgaCode: "KN033" },
      { name: "Rogo", lgaCode: "KN034" },
      { name: "Shanono", lgaCode: "KN035" },
      { name: "Sumaila", lgaCode: "KN036" },
      { name: "Takai", lgaCode: "KN037" },
      { name: "Tarauni", lgaCode: "KN038" },
      { name: "Tofa", lgaCode: "KN039" },
      { name: "Tsanyawa", lgaCode: "KN040" },
      { name: "Tudun Wada", lgaCode: "KN041" },
      { name: "Ungogo", lgaCode: "KN042" },
      { name: "Warawa", lgaCode: "KN043" },
      { name: "Wudil", lgaCode: "KN044" },
    ],
  },
  {
    id: 20,
    name: "Katsina",
    code: "KT",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Bakori", lgaCode: "KT001" },
      { name: "Batagarawa", lgaCode: "KT002" },
      { name: "Batsari", lgaCode: "KT003" },
      { name: "Baure", lgaCode: "KT004" },
      { name: "Bindawa", lgaCode: "KT005" },
      { name: "Charanchi", lgaCode: "KT006" },
      { name: "Dandume", lgaCode: "KT007" },
      { name: "Danja", lgaCode: "KT008" },
      { name: "Dan Musa", lgaCode: "KT009" },
      { name: "Daura", lgaCode: "KT010" },
      { name: "Dutsi", lgaCode: "KT011" },
      { name: "Dutsin Ma", lgaCode: "KT012" },
      { name: "Faskari", lgaCode: "KT013" },
      { name: "Funtua", lgaCode: "KT014" },
      { name: "Ingawa", lgaCode: "KT015" },
      { name: "Jibia", lgaCode: "KT016" },
      { name: "Kafur", lgaCode: "KT017" },
      { name: "Kaita", lgaCode: "KT018" },
      { name: "Kankara", lgaCode: "KT019" },
      { name: "Kankia", lgaCode: "KT020" },
      { name: "Katsina", lgaCode: "KT021" },
      { name: "Kurfi", lgaCode: "KT022" },
      { name: "Kusada", lgaCode: "KT023" },
      { name: "Mai'Adua", lgaCode: "KT024" },
      { name: "Malumfashi", lgaCode: "KT025" },
      { name: "Mani", lgaCode: "KT026" },
      { name: "Mashi", lgaCode: "KT027" },
      { name: "Matazu", lgaCode: "KT028" },
      { name: "Musawa", lgaCode: "KT029" },
      { name: "Rimi", lgaCode: "KT030" },
      { name: "Sabuwa", lgaCode: "KT031" },
      { name: "Safana", lgaCode: "KT032" },
      { name: "Sandamu", lgaCode: "KT033" },
      { name: "Zango", lgaCode: "KT034" },
    ],
  },
  {
    id: 21,
    name: "Kebbi",
    code: "KB",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Aleiro", lgaCode: "KB001" },
      { name: "Arewa", lgaCode: "KB002" },
      { name: "Argungu", lgaCode: "KB003" },
      { name: "Augie", lgaCode: "KB004" },
      { name: "Bagudo", lgaCode: "KB005" },
      { name: "Birnin Kebbi", lgaCode: "KB006" },
      { name: "Bunza", lgaCode: "KB007" },
      { name: "Dandi", lgaCode: "KB008" },
      { name: "Fakai", lgaCode: "KB009" },
      { name: "Gwandu", lgaCode: "KB010" },
      { name: "Jega", lgaCode: "KB011" },
      { name: "Kalgo", lgaCode: "KB012" },
      { name: "Koko/Besse", lgaCode: "KB013" },
      { name: "Maiyama", lgaCode: "KB014" },
      { name: "Ngaski", lgaCode: "KB015" },
      { name: "Sakaba", lgaCode: "KB016" },
      { name: "Shanga", lgaCode: "KB017" },
      { name: "Suru", lgaCode: "KB018" },
      { name: "Danko-Wasagu", lgaCode: "KB019" },
      { name: "Yauri", lgaCode: "KB020" },
      { name: "Zuru", lgaCode: "KB021" },
    ],
  },
  {
    id: 22,
    name: "Kogi",
    code: "KG",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Adavi", lgaCode: "KG001" },
      { name: "Ajaokuta", lgaCode: "KG002" },
      { name: "Ankpa", lgaCode: "KG003" },
      { name: "Bassa", lgaCode: "KG004" },
      { name: "Dekina", lgaCode: "KG005" },
      { name: "Ibaji", lgaCode: "KG006" },
      { name: "Idah", lgaCode: "KG007" },
      { name: "Igalamela Odolu", lgaCode: "KG008" },
      { name: "Ijumu", lgaCode: "KG009" },
      { name: "Kabba/Bunu", lgaCode: "KG010" },
      { name: "Kogi", lgaCode: "KG011" },
      { name: "Lokoja", lgaCode: "KG012" },
      { name: "Mopa Muro", lgaCode: "KG013" },
      { name: "Ofu", lgaCode: "KG014" },
      { name: "Ogori/Magongo", lgaCode: "KG015" },
      { name: "Okehi", lgaCode: "KG016" },
      { name: "Okene", lgaCode: "KG017" },
      { name: "Olamaboro", lgaCode: "KG018" },
      { name: "Omala", lgaCode: "KG019" },
      { name: "Yagba East", lgaCode: "KG020" },
      { name: "Yagba West", lgaCode: "KG021" },
    ],
  },
  {
    id: 23,
    name: "Kwara",
    code: "KW",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Asa", lgaCode: "KW001" },
      { name: "Baruten", lgaCode: "KW002" },
      { name: "Edu", lgaCode: "KW003" },
      { name: "Ekiti", lgaCode: "KW004" },
      { name: "Ifelodun", lgaCode: "KW005" },
      { name: "Ilorin East", lgaCode: "KW006" },
      { name: "Ilorin South", lgaCode: "KW007" },
      { name: "Ilorin West", lgaCode: "KW008" },
      { name: "Irepodun", lgaCode: "KW009" },
      { name: "Isin", lgaCode: "KW010" },
      { name: "Kaiama", lgaCode: "KW011" },
      { name: "Moro", lgaCode: "KW012" },
      { name: "Offa", lgaCode: "KW013" },
      { name: "Oke Ero", lgaCode: "KW014" },
      { name: "Oyun", lgaCode: "KW015" },
      { name: "Pategi", lgaCode: "KW016" },
    ],
  },
  {
    id: 24,
    name: "Lagos",
    code: "LA",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Agege", lgaCode: "LA001" },
      { name: "Ajeromi-Ifelodun", lgaCode: "LA002" },
      { name: "Alimosho", lgaCode: "LA003" },
      { name: "Amuwo-Odofin", lgaCode: "LA004" },
      { name: "Apapa", lgaCode: "LA005" },
      { name: "Badagry", lgaCode: "LA006" },
      { name: "Epe", lgaCode: "LA007" },
      { name: "Eti Osa", lgaCode: "LA008" },
      { name: "Ibeju-Lekki", lgaCode: "LA009" },
      { name: "Ifako-Ijaiye", lgaCode: "LA010" },
      { name: "Ikeja", lgaCode: "LA011" },
      { name: "Ikorodu", lgaCode: "LA012" },
      { name: "Kosofe", lgaCode: "LA013" },
      { name: "Lagos Island", lgaCode: "LA014" },
      { name: "Lagos Mainland", lgaCode: "LA015" },
      { name: "Mushin", lgaCode: "LA016" },
      { name: "Ojo", lgaCode: "LA017" },
      { name: "Oshodi-Isolo", lgaCode: "LA018" },
      { name: "Shomolu", lgaCode: "LA019" },
      { name: "Surulere", lgaCode: "LA020" },
    ],
  },
  {
    id: 25,
    name: "Nasarawa",
    code: "NA",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Akwanga", lgaCode: "NA001" },
      { name: "Awe", lgaCode: "NA002" },
      { name: "Doma", lgaCode: "NA003" },
      { name: "Karu", lgaCode: "NA004" },
      { name: "Keana", lgaCode: "NA005" },
      { name: "Keffi", lgaCode: "NA006" },
      { name: "Kokona", lgaCode: "NA007" },
      { name: "Lafia", lgaCode: "NA008" },
      { name: "Nasarawa", lgaCode: "NA009" },
      { name: "Nasarawa Egon", lgaCode: "NA010" },
      { name: "Obi", lgaCode: "NA011" },
      { name: "Toto", lgaCode: "NA012" },
      { name: "Wamba", lgaCode: "NA013" },
    ],
  },
  {
    id: 26,
    name: "Niger",
    code: "NG",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Agaie", lgaCode: "NG001" },
      { name: "Agwara", lgaCode: "NG002" },
      { name: "Bida", lgaCode: "NG003" },
      { name: "Borgu", lgaCode: "NG004" },
      { name: "Bosso", lgaCode: "NG005" },
      { name: "Chanchaga", lgaCode: "NG006" },
      { name: "Edati", lgaCode: "NG007" },
      { name: "Gbako", lgaCode: "NG008" },
      { name: "Gurara", lgaCode: "NG009" },
      { name: "Katcha", lgaCode: "NG010" },
      { name: "Kontagora", lgaCode: "NG011" },
      { name: "Lapai", lgaCode: "NG012" },
      { name: "Lavun", lgaCode: "NG013" },
      { name: "Magama", lgaCode: "NG014" },
      { name: "Mariga", lgaCode: "NG015" },
      { name: "Mashegu", lgaCode: "NG016" },
      { name: "Mokwa", lgaCode: "NG017" },
      { name: "Moya", lgaCode: "NG018" },
      { name: "Paikoro", lgaCode: "NG019" },
      { name: "Rafi", lgaCode: "NG020" },
      { name: "Rijau", lgaCode: "NG021" },
      { name: "Shiroro", lgaCode: "NG022" },
      { name: "Suleja", lgaCode: "NG023" },
      { name: "Tafa", lgaCode: "NG024" },
      { name: "Wushishi", lgaCode: "NG025" },
    ],
  },
  {
    id: 27,
    name: "Ogun",
    code: "OG",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Abeokuta North", lgaCode: "OG001" },
      { name: "Abeokuta South", lgaCode: "OG002" },
      { name: "Ado-Odo/Ota", lgaCode: "OG003" },
      { name: "Egbado North", lgaCode: "OG004" },
      { name: "Egbado South", lgaCode: "OG005" },
      { name: "Ewekoro", lgaCode: "OG006" },
      { name: "Ifo", lgaCode: "OG007" },
      { name: "Ijebu East", lgaCode: "OG008" },
      { name: "Ijebu North", lgaCode: "OG009" },
      { name: "Ijebu North East", lgaCode: "OG010" },
      { name: "Ijebu Ode", lgaCode: "OG011" },
      { name: "Ikenne", lgaCode: "OG012" },
      { name: "Imeko Afon", lgaCode: "OG013" },
      { name: "Ipokia", lgaCode: "OG014" },
      { name: "Obafemi Owode", lgaCode: "OG015" },
      { name: "Odeda", lgaCode: "OG016" },
      { name: "Odogbolu", lgaCode: "OG017" },
      { name: "Ogun Waterside", lgaCode: "OG018" },
      { name: "Remo North", lgaCode: "OG019" },
      { name: "Shagamu", lgaCode: "OG020" },
    ],
  },
  {
    id: 28,
    name: "Ondo",
    code: "OD",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Akoko North-East", lgaCode: "OD001" },
      { name: "Akoko North-West", lgaCode: "OD002" },
      { name: "Akoko South-East", lgaCode: "OD003" },
      { name: "Akoko South-West", lgaCode: "OD004" },
      { name: "Akure North", lgaCode: "OD005" },
      { name: "Akure South", lgaCode: "OD006" },
      { name: "Ese Odo", lgaCode: "OD007" },
      { name: "Idanre", lgaCode: "OD008" },
      { name: "Ifedore", lgaCode: "OD009" },
      { name: "Ilaje", lgaCode: "OD010" },
      { name: "Ile Oluji/Okeigbo", lgaCode: "OD011" },
      { name: "Irele", lgaCode: "OD012" },
      { name: "Odigbo", lgaCode: "OD013" },
      { name: "Okitipupa", lgaCode: "OD014" },
      { name: "Ondo West", lgaCode: "OD015" },
      { name: "Ondo East", lgaCode: "OD016" },
      { name: "Ose", lgaCode: "OD017" },
      { name: "Owo", lgaCode: "OD018" },
    ],
  },
  {
    id: 29,
    name: "Osun",
    code: "OS",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Aiyedaade", lgaCode: "OS001" },
      { name: "Atakunmosa East", lgaCode: "OS002" },
      { name: "Atakunmosa West", lgaCode: "OS003" },
      { name: "Boluwaduro", lgaCode: "OS004" },
      { name: "Boripe", lgaCode: "OS005" },
      { name: "Ede North", lgaCode: "OS006" },
      { name: "Ede South", lgaCode: "OS007" },
      { name: "Egbedore", lgaCode: "OS008" },
      { name: "Ejigbo", lgaCode: "OS009" },
      { name: "Gbonyin", lgaCode: "OS0010" },
      { name: "Ife Central", lgaCode: "OS011" },
      { name: "Ife East", lgaCode: "OS012" },
      { name: "Ife North", lgaCode: "OS013" },
      { name: "Ife South", lgaCode: "OS014" },
      { name: "Ifedayo", lgaCode: "OS015" },
      { name: "Ifelodun", lgaCode: "OS016" },
      { name: "Ila", lgaCode: "OS017" },
      { name: "Ilesa East", lgaCode: "OS018" },
      { name: "Ilesa West", lgaCode: "OS019" },
      { name: "Irepodun", lgaCode: "OS020" },
      { name: "Irewole", lgaCode: "OS021" },
      { name: "Isokan", lgaCode: "OS022" },
      { name: "Iwo", lgaCode: "OS023" },
      { name: "Obokun", lgaCode: "OS024" },
      { name: "Odo Otin", lgaCode: "OS025" },
      { name: "Ola Oluwa", lgaCode: "OS026" },
      { name: "Olorunda", lgaCode: "OS027" },
      { name: "Oriade", lgaCode: "OS028" },
      { name: "Orolu", lgaCode: "OS029" },
      { name: "Osogbo", lgaCode: "OS030" },
    ],
  },
  {
    id: 30,
    name: "Oyo",
    code: "OY",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Afijio", lgaCode: "OY001" },
      { name: "Akinyele", lgaCode: "OY002" },
      { name: "Atiba", lgaCode: "OY003" },
      { name: "Atisbo", lgaCode: "OY004" },
      { name: "Egbeda", lgaCode: "OY005" },
      { name: "Ibadan North", lgaCode: "OY006" },
      { name: "Ibadan North-East", lgaCode: "OY007" },
      { name: "Ibadan North-West", lgaCode: "OY008" },
      { name: "Ibadan South-East", lgaCode: "OY009" },
      { name: "Ibadan South-West", lgaCode: "OY010" },
      { name: "Ibarapa Central", lgaCode: "OY011" },
      { name: "Ibarapa East", lgaCode: "OY012" },
      { name: "Ibarapa North", lgaCode: "OY013" },
      { name: "Ido", lgaCode: "OY014" },
      { name: "Irepo", lgaCode: "OY015" },
      { name: "Iseyin", lgaCode: "OY016" },
      { name: "Itesiwaju", lgaCode: "OY017" },
      { name: "Iwajowa", lgaCode: "OY018" },
      { name: "Kajola", lgaCode: "OY019" },
      { name: "Lagelu", lgaCode: "OY020" },
      { name: "Ogbomosho North", lgaCode: "OY021" },
      { name: "Ogbomosho South", lgaCode: "OY022" },
      { name: "Ogo Oluwa", lgaCode: "OY023" },
      { name: "Olorunsogo", lgaCode: "OY024" },
      { name: "Oluyole", lgaCode: "OY025" },
      { name: "Ona Ara", lgaCode: "OY026" },
      { name: "Orelope", lgaCode: "OY027" },
      { name: "Ori Ire", lgaCode: "OY028" },
      { name: "Oyo East", lgaCode: "OY029" },
      { name: "Oyo West", lgaCode: "OY030" },
      { name: "Saki East", lgaCode: "OY031" },
      { name: "Saki West", lgaCode: "OY032" },
      { name: "Surulere", lgaCode: "OY033" },
    ],
  },
  {
    id: 31,
    name: "Plateau",
    code: "PL",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Barkin Ladi", lgaCode: "PL001" },
      { name: "Bassa", lgaCode: "PL002" },
      { name: "Bokkos", lgaCode: "PL003" },
      { name: "Jos East", lgaCode: "PL004" },
      { name: "Jos North", lgaCode: "PL005" },
      { name: "Jos South", lgaCode: "PL006" },
      { name: "Kanam", lgaCode: "PL007" },
      { name: "Kanke", lgaCode: "PL008" },
      { name: "Langtang North", lgaCode: "PL009" },
      { name: "Langtang South", lgaCode: "PL010" },
      { name: "Mangu", lgaCode: "PL011" },
      { name: "Mikang", lgaCode: "PL012" },
      { name: "Pankshin", lgaCode: "PL013" },
      { name: "Qua'an Pan", lgaCode: "PL014" },
      { name: "Riyom", lgaCode: "PL015" },
      { name: "Shendam", lgaCode: "PL016" },
      { name: "Wase", lgaCode: "PL017" },
    ],
  },
  {
    id: 32,
    name: "Rivers",
    code: "RV",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Abua/Odual", lgaCode: "RV001" },
      { name: "Ahoada East", lgaCode: "RV002" },
      { name: "Ahoada West", lgaCode: "RV003" },
      { name: "Akuku-Toru", lgaCode: "RV004" },
      { name: "Andoni", lgaCode: "RV005" },
      { name: "Asari-Toru", lgaCode: "RV006" },
      { name: "Bonny", lgaCode: "RV007" },
      { name: "Degema", lgaCode: "RV008" },
      { name: "Eleme", lgaCode: "RV009" },
      { name: "Emuoha", lgaCode: "RV010" },
      { name: "Etche", lgaCode: "RV011" },
      { name: "Gokana", lgaCode: "RV012" },
      { name: "Ikwerre", lgaCode: "RV013" },
      { name: "Khana", lgaCode: "RV014" },
      { name: "Obio/Akpor", lgaCode: "RV015" },
      { name: "Ogba/Egbema/Ndoni", lgaCode: "RV016" },
      { name: "Ogu/Bolo", lgaCode: "RV017" },
      { name: "Okrika", lgaCode: "RV018" },
      { name: "Omuma", lgaCode: "RV019" },
      { name: "Opobo/Nkoro", lgaCode: "RV020" },
      { name: "Oyigbo", lgaCode: "RV021" },
      { name: "Port Harcourt", lgaCode: "RV022" },
      { name: "Tai", lgaCode: "RV023" },
    ],
  },
  {
    id: 33,
    name: "Sokoto",
    code: "SK",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Binji", lgaCode: "SK001" },
      { name: "Bodinga", lgaCode: "SK002" },
      { name: "Dange Shuni", lgaCode: "SK003" },
      { name: "Gada", lgaCode: "SK004" },
      { name: "Goronyo", lgaCode: "SK005" },
      { name: "Gudu", lgaCode: "SK006" },
      { name: "Gwadabawa", lgaCode: "SK007" },
      { name: "Illela", lgaCode: "SK008" },
      { name: "Isa", lgaCode: "SK009" },
      { name: "Kebbe", lgaCode: "SK010" },
      { name: "Kware", lgaCode: "SK011" },
      { name: "Rabah", lgaCode: "SK012" },
      { name: "Sabon Birni", lgaCode: "SK013" },
      { name: "Shagari", lgaCode: "SK014" },
      { name: "Silame", lgaCode: "SK015" },
      { name: "Sokoto North", lgaCode: "SK016" },
      { name: "Sokoto South", lgaCode: "SK017" },
      { name: "Tambuwal", lgaCode: "SK018" },
      { name: "Tangaza", lgaCode: "SK019" },
      { name: "Tureta", lgaCode: "SK020" },
      { name: "Wamako", lgaCode: "SK021" },
      { name: "Wurno", lgaCode: "SK022" },
      { name: "Yabo", lgaCode: "SK023" },
    ],
  },
  {
    id: 34,
    name: "Taraba",
    code: "TR",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Ardo Kola", lgaCode: "TR001" },
      { name: "Bali", lgaCode: "TR002" },
      { name: "Donga", lgaCode: "TR003" },
      { name: "Gashaka", lgaCode: "TR004" },
      { name: "Gassol", lgaCode: "TR005" },
      { name: "Ibi", lgaCode: "TR006" },
      { name: "Jalingo", lgaCode: "TR007" },
      { name: "Karim Lamido", lgaCode: "TR008" },
      { name: "Kumi", lgaCode: "TR009" },
      { name: "Lau", lgaCode: "TR010" },
      { name: "Sardauna", lgaCode: "TR011" },
      { name: "Takum", lgaCode: "TR012" },
      { name: "Ussa", lgaCode: "TR013" },
      { name: "Wukari", lgaCode: "TR014" },
      { name: "Yorro", lgaCode: "TR015" },
      { name: "Zing", lgaCode: "TR016" },
    ],
  },
  {
    id: 35,
    name: "Yobe",
    code: "YB",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Bade", lgaCode: "YB001" },
      { name: "Bursari", lgaCode: "YB002" },
      { name: "Damaturu", lgaCode: "YB003" },
      { name: "Fika", lgaCode: "YB004" },
      { name: "Fune", lgaCode: "YB005" },
      { name: "Geidam", lgaCode: "YB006" },
      { name: "Gujba", lgaCode: "YB007" },
      { name: "Gulani", lgaCode: "YB008" },
      { name: "Jakusko", lgaCode: "YB009" },
      { name: "Karasuwa", lgaCode: "YB010" },
      { name: "Machina", lgaCode: "YB011" },
      { name: "Nangere", lgaCode: "YB012" },
      { name: "Nguru", lgaCode: "YB013" },
      { name: "Potiskum", lgaCode: "YB014" },
      { name: "Tarmuwa", lgaCode: "YB015" },
      { name: "Yunusari", lgaCode: "YB016" },
      { name: "Yusufari", lgaCode: "YB017" },
    ],
  },
  {
    id: 36,
    name: "Zamfara",
    code: "ZM",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Anka", lgaCode: "ZM001" },
      { name: "Bakura", lgaCode: "ZM002" },
      { name: "Birnin Magaji/Kiyaw", lgaCode: "ZM003" },
      { name: "Bukkuyum", lgaCode: "ZM004" },
      { name: "Bungudu", lgaCode: "ZM005" },
      { name: "Chafe", lgaCode: "ZM006" },
      { name: "Gummi", lgaCode: "ZM007" },
      { name: "Gusau", lgaCode: "ZM008" },
      { name: "Kaura Namoda", lgaCode: "ZM009" },
      { name: "Maradun", lgaCode: "ZM010" },
      { name: "Maru", lgaCode: "ZM011" },
      { name: "Shinkafi", lgaCode: "ZM012" },
      { name: "Talata Mafara", lgaCode: "ZM013" },
      { name: "Zurmi", lgaCode: "ZM014" },
    ],
  },
  {
    id: 37,
    name: "Federal Capital Territory",
    code: "FC",
    localGoverment: [
      { name: "Choose LGA..." },
      { name: "Abaji", lgaCode: "FC001" },
      { name: "Bwari", lgaCode: "FC002" },
      { name: "Gwagwalada", lgaCode: "FC003" },
      { name: "Kuje", lgaCode: "FC004" },
      { name: "Kwali", lgaCode: "FC005" },
      { name: "Abuja Municipal Area Council", lgaCode: "FC006" },
    ],
  },
];

export const campaignData = [
  {
    id: 1,
    title: "Offer on Dental Checkup",
    date: "3 days ago",
    type: "email",
    sendTo: "All Patients",
    action: {
      subject: "Delight patients with a free dental checkup",
      message:
        "Dear Patient, We are delighted to offer you a free dental checkup. Please visit our clinic to avail this offer. Thank you. and have a nice day. and welcome to our clinic.",
      subHeader: "Offer on Dental Checkup",
      header: "How to avail this offer?",
      footer: "This offer is valid till 30th June, 2021",
    },
  },
  {
    id: 2,
    title: "Britam Insurance Offer",
    date: "8 days ago",
    type: "whatsapp",
    sendTo: "Britam Patients",
    action: {
      message:
        "Hellow Patient, are you looking for a free dental checkup? We are delighted to offer you a free dental checkup. Please visit our clinic to avail this offer. Thank you.",
    },
  },
  {
    id: 3,
    title: "NHCF Insurance Offer",
    date: "10 days ago",
    type: "sms",
    sendTo: "NHCF Patients",
    action: {
      message: "Hola, Delight patient with NHCF Insurance, We are delighted to offer you a free dental checkup. Please visit our clinic to avail this offer. Thank you.",
    },
  },
  {
    id: 4,
    title: "Cash patients offer",
    date: "15 days ago",
    type: "sms",
    sendTo: "Cash Patients",
    action: {
      message: "Delight Patient, now get 50% off on dental checkup. Please visit our clinic to avail this offer. Thank you. and have a nice day. and welcome to our clinic.",
    },
  },
  {
    id: 5,
    title: "Braces Offer",
    date: "12 days ago",
    type: "email",
    sendTo: "Britam Patients",
    action: {
      subject: "Delight patients with a free dental checkup",
      message:
        "Dear Patient, Britam Insurance is delighted to offer you a free dental checkup. Please visit our clinic to avail this offer. Thank you. and have a nice day. and welcome to our clinic.",
      subHeader: "Braces Offer for Britam Patients",
      header: "Now get braces at 50% off",
      footer: "This offer is valid till 30th June, 2021",
    },
  },
  {
    id: 6,
    title: "Teeth Whitening Offer",
    date: "20 days ago",
    type: "whatsapp",
    sendTo: "All Patients",
    action: {
      message: "Hola, Delight patient with Teeth Whitening Offer, We are delighted to offer you a free dental checkup. Please visit our clinic to avail this offer. Thank you.",
    },
  },
];
export const servicesData = [
  {
    id: 1,
    name: "Select service.. ",
  },
  {
    id: 2,
    name: "Root Canal",
    price: 40000,
    date: "23 June, 2021",
    status: true,
  },
  {
    id: 3,
    name: "Teeth Whitening",
    price: 20000,
    date: "12 Jan, 2022",
    status: true,
  },
  {
    id: 4,
    name: "Dental Implants",
    price: 50000,
    date: "11 April, 2023",
    status: false,
  },
  {
    id: 5,
    name: "Dental Crowns",
    price: 34000,
    date: "10 Agst, 2021",
    status: true,
  },
  {
    id: 6,
    name: "Dental Bridges",
    price: 10400,
    date: "23 June, 2021",
    status: false,
  },
  {
    id: 7,
    name: "Dental Veneers",
    price: 150000,
    date: "09 Dec, 2023",
    status: false,
  },
  {
    id: 8,
    name: "Dental Braces",
    price: 23000,
    date: "05 Feb, 2019",
    status: true,
  },
  {
    id: 9,
    name: "Dental Sealants",
    price: 40000,
    date: "16 Nov, 2022",
    status: true,
  },
  {
    id: 10,
    name: "Dentures",
    price: 19000,
    date: "02 Jun, 2022",
    status: false,
  },
  {
    id: 11,
    name: "Tooth Extraction",
    price: 160000,
    date: "23 June, 2021",
    status: true,
  },
];

export const invoicesData = [
  {
    id: 206719,
    to: memberData[5],
    total: 6070,
    createdDate: "12/06/2021",
    dueDate: "16/06/2021",
    items: [
      {
        id: 1,
        name: servicesData[0].name,
        price: 500,
        description: "Root Canal Treatment with X-Ray and Consultation is included in this package",
      },
      {
        id: 2,
        name: servicesData[1].name,
        price: 300,
        description: "Teeth Whitening Treatment",
      },
      {
        id: 3,
        name: servicesData[2].name,
        price: 260,
        description: "Dental Implants Treatment",
      },
      {
        id: 4,
        name: servicesData[3].name,
        price: 190000,
        description: "Dental Crowns Treatment",
      },
      {
        id: 5,
        name: servicesData[4].name,
        price: 15000,
        description: "Dental Bridges Treatment",
      },
    ],
  },
  {
    id: 198772,
    to: memberData[6],
    total: 5000,
    createdDate: "10/02/2023",
    dueDate: "14/02/2023",
    items: [
      {
        id: 1,
        name: servicesData[3].name,
        price: 190000,
        description: "Dental Crowns Treatment",
      },
      {
        id: 2,
        name: servicesData[4].name,
        price: 15000,
        description: "Dental Bridges Treatment",
      },
      {
        id: 3,
        name: servicesData[8].name,
        price: 20000,
        description: "Dentures Treatment",
      },
      {
        id: 4,
        name: servicesData[3].name,
        price: 190000,
        description: "Dental Crowns Treatment",
      },
    ],
  },
  {
    id: 456789,
    to: memberData[7],
    total: 10000,
    createdDate: "09/01/2023",
    dueDate: "13/01/2023",
    items: [
      {
        id: 1,
        name: servicesData[5].name,
        price: 5000,
        description: "Dental Veneers Treatment",
      },
      {
        id: 2,
        name: servicesData[6].name,
        price: 16000,
        description: "Dental Braces Treatment",
      },
      {
        id: 3,
        name: servicesData[7].name,
        price: 10000,
        description: "Dental Sealants Treatment",
      },
      {
        id: 4,
        name: servicesData[8].name,
        price: 20000,
        description: "Dentures Treatment",
      },
    ],
  },
  {
    id: 876543,
    to: memberData[4],
    total: 19000,
    createdDate: "08/01/2023",
    dueDate: "12/01/2023",
    items: [
      {
        id: 1,
        name: servicesData[5].name,
        price: 5000,
        description: "Dental Veneers Treatment",
      },
      {
        id: 2,
        name: servicesData[6].name,
        price: 16000,
        description: "Dental Braces Treatment",
      },
      {
        id: 3,
        name: servicesData[7].name,
        price: 10000,
        description: "Dental Sealants Treatment",
      },
      {
        id: 4,
        name: servicesData[8].name,
        price: 20000,
        description: "Dentures Treatment",
      },
      {
        id: 5,
        name: servicesData[3].name,
        price: 190000,
        description: "Dental Crowns Treatment",
      },
      {
        id: 6,
        name: servicesData[4].name,
        price: 15000,
        description: "Dental Bridges Treatment",
      },
    ],
  },
];

export const appointmentsData = [
  {
    id: 1,
    time: "2 hrs later",
    user: memberData[4],
    from: "10:00 AM",
    to: "12:00 PM",
    hours: 2,
    status: "Pending",
    doctor: memberData[0],
    date: "Jun 12, 2021",
  },
  {
    id: 2,
    time: "1 hrs ago",
    user: memberData[5],
    from: "13:00 Pm",
    to: "18:00 PM",
    hours: 5,
    status: "Cancel",
    doctor: memberData[1],
    date: "Feb 24, 2021",
  },
  {
    id: 3,
    time: "2 hrs ago",
    user: memberData[6],
    from: "10:00 AM",
    to: "12:00 PM",
    hours: 2,
    status: "Approved",
    doctor: memberData[2],
    date: "Mar 12, 2023",
  },
  {
    id: 4,
    time: "3 hrs later",
    user: memberData[7],
    from: "06:00 AM",
    to: "08:00 AM",
    hours: 3,
    status: "Pending",
    doctor: memberData[3],
    date: "Apr 06, 2023",
  },
  {
    id: 5,
    time: "4 hrs ago",
    user: memberData[3],
    from: "10:00 AM",
    to: "12:00 PM",
    hours: 7,
    status: "Approved",
    doctor: memberData[4],
    date: "May 18, 2023",
  },
];

export const transactionData = [
  {
    id: 1,
    user: memberData[0],
    date: "Mar 12, 2022",
    amount: 1000,
    status: "Paid",
    method: "Cash",
    doctor: memberData[3],
  },
  {
    id: 2,
    user: memberData[1],
    date: "Agus 12, 2023",
    amount: 2300,
    status: "Paid",
    method: "NHCF",
    doctor: memberData[4],
  },
  {
    id: 3,
    user: memberData[2],
    date: "Jan 06, 2024",
    amount: 1200,
    status: "Pending",
    method: "Britam",
    doctor: memberData[5],
  },
  {
    id: 4,
    user: memberData[3],
    date: "Feb 18, 2025",
    amount: 1400,
    status: "Cancel",
    method: "NHCF",
    doctor: memberData[6],
  },
  {
    id: 5,
    user: memberData[4],
    date: "Mar 12, 2026",
    amount: 1230,
    status: "Pending",
    method: "Cash",
    doctor: memberData[7],
  },
  {
    id: 6,
    user: memberData[5],
    date: "Apr 12, 2027",
    amount: 1000,
    status: "Paid",
    method: "NHCF",
    doctor: memberData[0],
  },
  {
    id: 7,
    user: memberData[6],
    date: "May 12, 2028",
    amount: 8900,
    status: "Cancel",
    method: "Britam",
    doctor: memberData[1],
  },
  {
    id: 8,
    user: memberData[7],
    date: "Jun 12, 2029",
    amount: 1000,
    status: "Pending",
    method: "Britam",
    doctor: memberData[2],
  },
];

export const dashboardCards = [
  {
    id: 1,
    title: "Total Patients",
    icon: TbUsers,
    value: 1600,
    percent: 45.06,
    color: ["bg-subMain", "text-subMain", "#66B5A3"],
    datas: [92, 80, 45, 15, 49, 77, 70, 51, 110, 20, 90, 60],
  },
  {
    id: 2,
    title: "Appointments",
    icon: TbCalendar,
    value: 130,
    percent: 25.06,
    color: ["bg-yellow-500", "text-yellow-500", "#F9C851"],
    datas: [20, 50, 75, 15, 108, 97, 70, 41, 50, 20, 90, 60],
  },
  {
    id: 3,
    title: "Prescriptions",
    icon: TbFile,
    value: 4160,
    percent: 65.06,
    color: ["bg-green-500", "text-green-500", "#34C759"],
    datas: [92, 80, 45, 15, 49, 77, 70, 51, 110, 20, 90, 60],
  },
  {
    id: 4,
    title: "Total Earnings",
    icon: MdOutlineAttachMoney,
    value: 4590,
    percent: 45.06,
    color: ["bg-red-500", "text-red-500", "#FF3B30"],
    datas: [20, 50, 75, 15, 108, 97, 70, 41, 50, 20, 90, 60],
  },
];

export const notificationsData = [
  {
    id: 1,
    action: 1,
    user: memberData[0],
    time: "2 hours ago",
  },
  {
    id: 2,
    action: 2,
    user: memberData[1],
    time: "2 days ago",
  },
  {
    id: 3,
    action: 1,
    user: memberData[2],
    time: "3 days ago",
  },
  {
    id: 4,
    action: 2,
    user: memberData[3],
    time: "4 days ago",
  },
];

export const shareData = [
  {
    id: 1,
    icon: HiOutlineMail,
    title: "Email",
    description: "Send to patient email address",
  },
  {
    id: 2,
    icon: MdOutlineTextsms,
    title: "SMS",
    description: "Send to patient phone number",
  },
  {
    id: 3,
    icon: FaWhatsapp,
    title: "WhatsApp",
    description: "Send to patient WhatsApp account",
  },
  {
    id: 4,
    icon: FaTelegramPlane,
    title: "Telegram",
    description: "Send to patient Telegram account",
  },
];

export const medicineData = [
  {
    id: 1,
    name: "Paracetamol",
    measure: "Tablet",
    stock: 400,
    price: 1000,
    status: "Available",
    instraction: "After meal",
  },
  {
    id: 2,
    name: "Amoxicillin",
    measure: "Capsule",
    stock: 200,
    price: 2300,
    status: "Available",
    instraction: "After meal",
  },
  {
    id: 3,
    name: "Ibuprofen",
    measure: "mm",
    stock: 0,
    price: 5000,
    status: "Out of stock",
    instraction: "Before meal",
  },
  {
    id: 4,
    name: "Aspirin",
    measure: "cm",
    stock: 370,
    price: 3500,
    status: "Available",
    instraction: "After meal",
  },
  {
    id: 5,
    name: "Diazepam",
    measure: "gm",
    stock: 0,
    price: 12000,
    status: "Out of stock",
    instraction: "Before meal",
  },
  {
    id: 6,
    name: "Lorazepam",
    measure: "mg",
    stock: 123,
    price: 15500,
    status: "Available",
    instraction: "Before meal",
  },
  {
    id: 7,
    name: "Codeine",
    measure: "ml",
    stock: 1,
    price: 30000,
    status: "Available",
    instraction: "After meal",
  },
  {
    id: 8,
    name: "Tramadol",
    measure: "lb",
    stock: 0,
    price: 200,
    status: "Out of stock",
    instraction: "Before meal",
  },
];

export const patientTab = [
  {
    id: 1,
    title: "Medical Records",
    icon: TbChartHistogram,
  },
  {
    id: 2,
    title: "Appointments",
    icon: BiCalendar,
  },
  {
    id: 3,
    title: "Invoices",
    icon: RiFileList3Line,
  },
  {
    id: 4,
    title: "Payments",
    icon: RiMoneyDollarCircleLine,
  },
  {
    id: 5,
    title: "Images",
    icon: RiImageLine,
  },
  {
    id: 6,
    title: "Dental Chart",
    icon: RiStethoscopeLine,
  },
  {
    id: 7,
    title: "Patient Information",
    icon: RiUserLine,
  },
  {
    id: 8,
    title: "Health Information",
    icon: RiHeartLine,
  },
];

export const doctorTab = [
  {
    id: 1,
    title: "Personal Information",
    icon: RiUserLine,
  },
  {
    id: 2,
    title: "Patients",
    icon: BiUserPlus,
  },
  {
    id: 3,
    title: "Appointments",
    icon: BiCalendar,
  },
  {
    id: 4,
    title: "Payments",
    icon: RiMoneyDollarCircleLine,
  },
  {
    id: 5,
    title: "Invoices",
    icon: RiFileList3Line,
  },
  {
    id: 6,
    title: "Access Control",
    icon: TbLockAccess,
  },
  {
    id: 7,
    title: "Change Password",
    icon: RiLockPasswordLine,
  },
];

export const medicalRecodData = [
  {
    id: 1,
    date: "13, Jan 2021",
    amount: 150000,
    data: [
      {
        id: 1,
        title: "Complaint",
        value: "Bleeding Gums, Toothache, bad breath",
      },
      {
        id: 2,
        title: "Diagnosis",
        value: "Gingivitis, Caries, Periodontitis",
      },
      {
        id: 3,
        title: "Treatment",
        value: "Filling, Post&Core, Implant, Extraction",
      },
      {
        id: 4,
        title: "Prescription",
        value: "Paracetamol, Amoxicillin, Ibuprofen, Aspirin",
      },
    ],
    attachments: ["https://placehold.it/300x300", "https://placehold.it/300x300", "https://placehold.it/300x300", "https://placehold.it/300x300"],
    vitalSigns: ["Blood Pressure: 120/80 mmHg", "Pulse Rate: 80 bpm", "Respiratory Rate: 16 bpm", "Temperature: 36.5 °C", "Oxygen Saturation: 98%"],
  },
  {
    id: 2,
    date: "10, Feb 2022",
    amount: 300000,
    data: [
      {
        id: 1,
        title: "Complaint",
        value: "Food impaction, Replacing Missing Teeth, bad breath",
      },
      {
        id: 2,
        title: "Diagnosis",
        value: "Caries, Periodontitis, Malocclusion",
      },
      {
        id: 3,
        title: "Treatment",
        value: "Superficial Scaling, Root Planing, Extraction",
      },
      {
        id: 4,
        title: "Prescription",
        value: "Benzocaine, Lidocaine, Mepivacaine, Prilocaine",
      },
    ],
    attachments: ["https://placehold.it/300x300", "https://placehold.it/300x300", "https://placehold.it/300x300", "https://placehold.it/300x300"],
    vitalSigns: ["Weight: 60 kg", "Height: 170 cm", "BMI: 20.76 kg/m2", "Blood Pressure: 120/80 mmHg"],
  },
  {
    id: 3,
    date: "20, Mar 2022",
    amount: 500000,
    data: [
      {
        id: 1,
        title: "Complaint",
        value: "Broken Teeth, Bridge, Cap in the front teeth",
      },
      {
        id: 2,
        title: "Diagnosis",
        value: "Unspecified Gingival Recession, Unspecified Caries",
      },
      {
        id: 3,
        title: "Treatment",
        value: "Consultation, Scaling, Root Planing, Extraction",
      },
      {
        id: 4,
        title: "Prescription",
        value: "Gingival Gel, Chlorhexidine, Fluoride, Calcium",
      },
    ],
    attachments: ["https://placehold.it/300x300", "https://placehold.it/300x300", "https://placehold.it/300x300", "https://placehold.it/300x300"],
    vitalSigns: ["Temperature: 36.5 °C", "Oxygen Saturation: 98%", "Blood Pressure: 120/80 mmHg", "Pulse Rate: 80 bpm", "Respiratory Rate: 16 bpm"],
  },
  {
    id: 4,
    date: "10, Apr 2022",
    amount: 760000,
    data: [
      {
        id: 1,
        title: "Complaint",
        value: "Toothache, bad breath, Bleeding Gums",
      },
      {
        id: 2,
        title: "Diagnosis",
        value: "Necrotizing Ulcerative Gingivitis, Periodontitis",
      },
      {
        id: 3,
        title: "Treatment",
        value: "Crowns, Bridges, Veneers, Implants",
      },
      {
        id: 4,
        title: "Prescription",
        value: "Tramadol, Codeine, Morphine, Oxycodone",
      },
    ],
    attachments: ["https://placehold.it/300x300", "https://placehold.it/300x300", "https://placehold.it/300x300", "https://placehold.it/300x300"],
    vitalSigns: ["Sugar Level: 120 mg/dL", "Oxygen Saturation: 98%", "Cholesterol: 200 mg/dL", "Blood Pressure: 120/80 mmHg"],
  },
];

export const doctorsData = [
  {
    id: 1,
    user: memberData[0],
    title: "Dr.",
  },
  {
    id: 2,
    user: memberData[1],
    title: "Dr.",
  },
  {
    id: 3,
    user: memberData[2],
    title: "Dr.",
  },
  {
    id: 4,
    user: memberData[3],
    title: "Dr.",
  },
];

export const receptionsData = [
  {
    id: 1,
    user: memberData[6],
    title: "Dr.",
  },
  {
    id: 2,
    user: memberData[7],
    title: "Dr.",
  },
  {
    id: 3,
    user: memberData[5],
    title: "Dr.",
  },
  {
    id: 4,
    user: memberData[4],
    title: "Dr.",
  },
  {
    id: 5,
    user: memberData[2],
    title: "Dr.",
  },
  {
    id: 6,
    user: memberData[1],
    title: "Dr.",
  },
];
